version: '3.8'

services:
  frontend:
    image: ghcr.io/funke09/tachrone-frontend:dev
    container_name: tachrone-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tachrone-network
    restart:  on-failure

  backend:
    image: ghcr.io/funke09/tachrone-backend:dev
    container_name: tachrone-backend
    expose:
      - "8080"
    networks:
      - tachrone-network
    env_file:
      - .env
    restart:  on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  tachrone-network:
    driver: bridge

